version: '3.7'

services:

  test_postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=habrpguser
      - POSTGRES_PASSWORD=pgpwd4habr
      - POSTGRES_DB=test
    ports:
      - '5432:5432'